name: Go
on:
  push:
    branches:
      - "master"
      - "develop"
      - "feature/**"
      - "release/**"
      - "hotfix/**"
      - "bugfix/**"
  pull_request:
    branches: 
      - "master"
      - "develop"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      - name: Build
        run: go build -v ./cmd
      - name: Test with the Go CLI
        run: go test
