name: Go CI

on:
  push:
    branches:
      - "master"
      - "develop"
      - "feature/**"
      - "release/**"
      - "hotfix/**"
      - "bugfix/**"
  pull_request:
    branches:
      - "master"
      - "develop"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'

      - name: Clean old build artifacts
        run: rm -rf ./cmd/myapp

      - name: Build
        run: go build -o myapp ./cmd/main.go

      - name: Run tests
        run: go test -v ./...
